version: '3'

services:
    web:
        build: . 
        command: python accountability_project/manage.py runserver 0.0.0.0:8000 
        volumes:
            - .:/code 
        ports:
            - "8000:8000"
        
        depends_on:
            - db
    db:
        image: postgres 
        container_name: db
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes: 
            - pg-data:/var/lib/postgresql/data/
volumes: 
    pg-data:
        driver: local